name: Integración Continua Java

# ¿Cuándo se ejecuta esto?
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# ¿Qué tareas va a realizar?
jobs:
  build:
    runs-on: ubuntu-latest # Máquina virtual donde se ejecutará

    steps:
    - name: 1. Descargar el código del repositorio
      uses: actions/checkout@v4

    - name: 2. Configurar el entorno de Java (JDK 25)
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temuri'

    - name: 3. Ejecutar las pruebas unitarias con Maven
      run: mvn test
      working-directory: ./Ejemplo-CI